version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finances
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./backend
    volumes:
      - ./backend:/src
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=finances;Username=user;Password=password
    depends_on:
      - db
    ports:
      - "3000:8080"
  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development


volumes:
  pgdata:
